config/routes.rb
Funstation::Application.routes.draw do
  resource :session
  resources :users

  resources :messages
  root :to => 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :user_id
  
  belongs_to :user
  
  validates :user, :presence => true
  validates :content, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :name, :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  
  def sign_in(user)
    session[:user_id] = user.id
  end
  
  def sign_out
    session[:user_id] = nil
  end
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  helper_method :current_user
  
  def signed_in?
    current_user
  end
  helper_method :signed_in?
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def index
    @messages = Message.all
  end
  
  def create
    @message = Message.new(params[:message])
    @message.user = current_user
    @message.save

    redirect_to messages_path
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    @user = User.find_by_email(params[:email])
    
    if @user && @user.authenticate(params[:password])
      sign_in(@user)
      
      flash[:success] = "Welcome back #{@user.name}"
      redirect_to root_path
    else
      flash[:error] = "Invalid email address and/or password"
      render :new
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new params[:user]
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Funstation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<header style='background-color: #DDD; width: 100%; height: 120px'>
  <%- if signed_in? %>
    Signed in as <%= current_user.name %>
    |
    <%= link_to 'Sign out', session_path, :method => :delete %>
  <%- else %>
    <%= link_to 'Sign in', new_session_path %>
  <% end %>
</header>

<% if flash.present? %>
  <ul id="flash">
    <% flash.each do |kind, message| %>
      <li class="<%= kind %>"><%= message %></li>
    <% end %>
  </ul>
<% end%>
<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<h2>Funstation Message Board</h2>
<ul>
	<% @messages.each do |message| %>
		<li>
		  <em><%= message.user.name %> said <%= time_ago_in_words message.created_at%> ago</em>
		  <%= simple_format message.content %>
		</li>
	<% end %>
</ul>

<%if signed_in? %>
  <%= form_for Message.new do |f| %>
  	<div>
  		<%= f.label :content %>
  		<%= f.text_area :content %>
  	</div>
  	<div>
  	  <%= f.submit %>
  	</div>
  <% end %>
<%else %>
  Please sign in to post.
<%end %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <div>
    <%= f.submit "Sign up" %>
  </div>
<% end %>